name: Continuous Integration
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Bio7
      uses: actions/checkout@v4

    - name: Set up OpenJDK with OpenJFX
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        java-package: 'jdk+fx'

    - name: Build with Maven
      run: mvn -f com.eco.bio7.aggregator/pom.xml install --batch-mode --no-transfer-progress
